### ISSUE TITLE
NetCore 3.1 - System.InvalidOperationException : 'Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger` ....

### ISSUE THREAD

**Issue by Nonobis** [Deblokt/IdentityServer4Demos#2]
Error On NetCore 3.1

System.InvalidOperationException : 'Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[Microsoft.AspNetCore.Identity.UserManager`1[IdentityServer.Models.ApplicationUser]]' while attempting to activate 'Microsoft.AspNetCore.Identity.UserManager`1[IdentityServer.Models.ApplicationUser]'.'

Class Users, in EnsureSeedData 

var context = scope.ServiceProvider.GetService<IdentityDbContext>();
                    context.Database.Migrate();

                    var userMgr = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
                    var defaultAdmin = userMgr.FindByNameAsync("admin").Result;

any how to solve this error ?
Great Tutorials by the way !

**Comment by Nonobis** [comment]
Fixed with DI of UserManager From StartUp

**Comment by Ihavenowand** [comment]
Hello.

I am also facing this issue.

Can you please post working code example.

thanks

**Comment by kalisi97** [comment]
Could you please post the working code here? 

Facing with the same issue

**Comment by kalisi97** [comment]
> Hello.
> 
> I am also facing this issue.
> 
> Can you please post working code example.
> 
> thanks


Solved with adding services.AddLogging(); to Seed class
